  CREATE TABLE SKILLS (
        SKILL_ID        NUMBER(10)	        PRIMARY KEY,
        SKILL_NAME  	VARCHAR2(50)	    NOT NULL
 );
 
  CREATE TABLE REGION_CITY(
    RESUME_ID   NUMBER(10),
    CITY_ID	    NUMBER(10)	    PRIMARY KEY,
    CITY_NAME	VARCHAR2(30),
    FOREIGN KEY (RESUME_ID) REFERENCES RESUME(RESUME_ID)
 );
 
  CREATE TABLE REGION_DISTRICT(
    CITY_ID	            NUMBER(10),
    DISTRICT_ID	        NUMBER(10)	    PRIMARY KEY,
    DISTRICT_NAME	    VARCHAR2(30)	NOT NULL,
    FOREIGN KEY (CITY_ID) REFERENCES REGION_CITY (CITY_ID)
 );
 
 CREATE TABLE USERS (
        USER_ID    	            VARCHAR2(30)	   PRIMARY KEY,
        USER_NAME	            VARCHAR2(30)	   NOT NULL,
        USER_PW	                VARCHAR2(30)	   NOT NULL,
        USER_BIRTHDATE	        VARCHAR2(30)	   NOT NULL,
        USER_GENDER	            VARCHAR2(30)	   NOT NULL,
        USER_TEL	            VARCHAR2(30)       NOT NULL
 );
 
 CREATE TABLE RESUME(
        USER_ID	        VARCHAR2(30),
        RESUME_ID	    NUMBER(10)	        PRIMARY KEY,
        RESUME_TITLE	VARCHAR2(100)	    NOT NULL,       
        COVER_LETTER	VARCHAR2(1000)      NOT NULL,
        RESUME_CDATE	DATE	            DEFAULT SYSDATE,
        RESUME_FDATE	DATE,
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
 );
 
  CREATE TABLE RESUME_CAREER(
    RESUME_ID           NUMBER(10),
    CAREER_ID	        NUMBER(10)	    PRIMARY KEY,
    CAREER_CNAME	    VARCHAR2(50)	NOT NULL,
    CAREER_DEPARTMENT	VARCHAR2(50)	NOT NULL,
    CAREER_JOP	        VARCHAR2(50)	NOT NULL,
    CAREER_DESCRIPTION 	VARCHAR2(1000)	NOT NULL,
    CAREER_SDATE	    VARCHAR2(50)	NOT NULL,
    CAREER_EDATE	    DATE,
    FOREIGN KEY (RESUME_ID) REFERENCES RESUME(RESUME_ID)
 );
 
 CREATE TABLE RESUME_SKILLS (
        RESUME_SID      NUMBER(10)      PRIMARY KEY,
        RESUME_ID	    NUMBER(10),
        SKILL_ID  	    NUMBER(10),
        FOREIGN KEY (RESUME_ID) REFERENCES RESUME(RESUME_ID),
        FOREIGN KEY (SKILL_ID) REFERENCES SKILLS(SKILL_ID)
 );
 
  CREATE TABLE COMPANIES(
    COMPANY_ID	    VARCHAR2(30)	    PRIMARY KEY,
    COMPANY_PW	    VARCHAR2(30)	    NOT NULL,
    COMPANY_NAME	VARCHAR2(30)	    NOT NULL,
    COMPANY_NUM	    VARCHAR2(30)	    NOT NULL UNIQUE,
    COMPANY_TEL	    VARCHAR2(30)	    NOT NULL,
    REP_NAME	    VARCHAR2(30)	    NOT NULL,
    COMPANY_EMAIL	VARCHAR2(300)	    NOT NULL,
    COMPANY_POINT	NUMBER(10, 2)	    DEFAULT 0
 );
 
  CREATE TABLE POST (
    POST_ID	            NUMBER(10)	    PRIMARY KEY,
    COMPANY_ID	        VARCHAR2(30),
    POST_TITLE	        VARCHAR2(50)	NOT NULL,
    POST_CONTENT	    VARCHAR2(1000)	NOT NULL,
    POST_HIT	        NUMBER(10)	    DEFAULT 0,
    POST_CDATE	        DATE	        DEFAULT SYSDATE,
    POST_FDATE	        DATE,
    FOREIGN KEY (COMPANY_ID)    REFERENCES COMPANIES(COMPANY_ID)
 );
 
  CREATE TABLE BENEFITS (
    BENEFIT_ID	    NUMBER(10)	    PRIMARY KEY,
    BENEFIT_NAME	VARCHAR2(30)	
 );
 
  CREATE TABLE POST_BENEFITS(
    CBENEFIT_ID	NUMBER(10)	PRIMARY KEY,
    BENEFIT_ID	NUMBER(10),
    POST_ID	    NUMBER(10),
    FOREIGN KEY (BENEFIT_ID)    REFERENCES BENEFITS(BENEFIT_ID),
    FOREIGN KEY (POST_ID)       REFERENCES POST(POST_ID)
 );
 
   CREATE TABLE EMPLOYMENT(
    EMP_ID	    NUMBER(10)	        PRIMARY KEY,
    EMP_NAME	VARCHAR2(30)	
 );
 
   CREATE TABLE POST_EMPLOYMENT(
    POSTEMP_ID	NUMBER(10)	PRIMARY KEY,
    POST_ID	    NUMBER(10),
    EMP_ID	    NUMBER(10),
    FOREIGN KEY (POST_ID)   REFERENCES POST(POST_ID),
    FOREIGN KEY (EMP_ID)    REFERENCES EMPLOYMENT(EMP_ID)
 );
 
 
 