 CREATE TABLE USERS (
        USER_ID    	            VARCHAR2(30)	   PRIMARY KEY,
        USER_NAME	            VARCHAR2(30)	   NOT NULL,
        USER_PW	                VARCHAR2(30)	   NOT NULL,
        USER_BIRTHDATE	    VARCHAR2(30)	   NOT NULL,
        USER_GENDER	        VARCHAR2(30)	   NOT NULL,
        USER_TEL	                VARCHAR2(30)    NOT NULL
 );
 /*
 INSERT INTO users (
    USER_ID,
    USER_NAME,
    USER_PW,
    USER_DATE,
    USER_GENDER,
    USER_TEL
) VALUES (
    'project1',
    '유저1',
    '1234',
    '20000202',
    '남',
    '01012341234'
);
COMMIT; 
*/

/*
 CREATE TABLE RESUME(
         RESUME_NUM	    NUMBER(10)	        PRIMARY KEY,
        USER_ID	            VARCHAR2(30),
        RESUME_TITLE	    VARCHAR2(100)	NOT NULL,
        CAREER_NUM	    NUMBER(10)	        REFERENCES USERS(USER_ID),
        CITY_ID	            NUMBER(10)	        REFERENCES USERS(USER_ID),
        DISTRICT_ID	        NUMBER(10)	        REFERENCES USERS(USER_ID),
        COVER_LETTER	    VARCHAR2(1000)  NOT NULL,
        RESUME_CDATE	    DATE	                DEFAULT SYSDATE,
        RESUME_FDATE	    DATE,
        FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
 );*/
 
 CREATE TABLE SKILLS (
        SKILL_NUM	    NUMBER(10)	    PRIMARY KEY,
        SKILL_NAME  	VARCHAR2(50)	    NOT NULL
 );
 /*
 INSERT INTO SKILLS VALUES (1,'자바');
 COMMIT;
 */
 
 CREATE TABLE REGION_CITY(
    CITY_ID	    NUMBER(10)	PRIMARY KEY,
    CITY_NAME	VARCHAR2(30)
 );
 /*INSERT INTO REGION_CITY VALUES(2,'서울');
 COMMIT;*/
 
 CREATE TABLE REGION_DISTRICT(
    DISTRICT_ID	        NUMBER(10)	PRIMARY KEY,
    DISTRICT_NAME	    VARCHAR2(30)	NOT NULL,
    CITY_ID	            NUMBER(10),
    FOREIGN KEY (CITY_ID) REFERENCES REGION_CITY (CITY_ID)
 );
 /*
  INSERT INTO REGION_DISTRICT VALUES(3,'서울우유',2);
 COMMIT;
 SELECT RC.CITY_ID,RC.CITY_NAME ,RD.DISTRICT_NAME FROM REGION_DISTRICT RD LEFT JOIN REGION_CITY RC ON RD.CITY_ID = RC.CITY_ID WHERE RC.CITY_ID = 1  ;*/
 
 CREATE TABLE COMPANIES(
    COMPANY_ID	    VARCHAR2(30)	    PRIMARY KEY,
    COMPANY_PW	    VARCHAR2(30)	    NOT NULL,
    COMPANY_NAME	VARCHAR2(30)	    NOT NULL,
    COMPANY_NUM	VARCHAR2(30)	    NOT NULL UNIQUE,
    COMPANY_TEL	    VARCHAR2(30)	    NOT NULL,
    REP_NAME	        VARCHAR2(30)	    NOT NULL,
    COMPANY_EMAIL	VARCHAR2(300)	NOT NULL,
    COMPANY_POINT	NUMBER(10, 2)	    DEFAULT 0
 );
 /*
 INSERT INTO COMPANIES VALUES('qwer123','1234','동신유압','123456789101112','0553277581','춘봉시치','kum@naver.com',0);
 COMMIT;*/
 
 CREATE TABLE BENEFITS (
    BENEFIT_ID	    NUMBER(10)	PRIMARY KEY,
    BENEFIT_NAME	VARCHAR2(30)	
 );
 /*INSERT INTO BENEFITS VALUES(1,'기숙사');
 COMMIT;*/
 
 CREATE TABLE EMPLOYMENT(
    EMP_ID	    NUMBER(10)	PRIMARY KEY,
    EMP_NAME	VARCHAR2(30)	
 );
 
/* INSERT INTO EMPLOYMENT VALUES(1,'정규직');
 COMMIT;*/
 
 CREATE TABLE POST (
    POST_ID	            NUMBER(10)	    PRIMARY KEY,
    COMPANY_ID	    VARCHAR2(30),
    POST_TITLE	        VARCHAR2(50)	    NOT NULL,
    POST_CONTENT	    VARCHAR2(1000)	NOT NULL,
    EMP_ID	            NUMBER(10),
    CITY_ID	            NUMBER(10),
    DISTRICT_ID	        NUMBER(10),
    BENEFIT_ID	        NUMBER(10),
    POST_HIT	            NUMBER(10)	    DEFAULT 0,
    POST_CDATE	        DATE	                DEFAULT SYSDATE,
    POST_FDATE	        DATE,
    FOREIGN KEY (COMPANY_ID)    REFERENCES COMPANIES(COMPANY_ID),
    FOREIGN KEY (EMP_ID)            REFERENCES EMPLOYMENT(EMP_ID),
    FOREIGN KEY (CITY_ID)            REFERENCES REGION_CITY(CITY_ID),
    FOREIGN KEY (DISTRICT_ID)      REFERENCES REGION_DISTRICT(DISTRICT_ID),
    FOREIGN KEY (BENEFIT_ID)        REFERENCES BENEFITS(BENEFIT_ID)
 );
 /*
 INSERT INTO post (
    POST_ID,
    COMPANY_ID,
    POST_TITLE,
    POST_CONTENT,
    EMP_ID,
    CITY_ID,
    DISTRICT_ID,
    BENEFIT_ID
) VALUES (
    1,
    'qwer123',
    'QWER DF지롱',
    'D점멸입니다. 존중해주세요.',
    1,
    1,
    1,
    1
);
COMMIT;*/

SELECT P.POST_ID, P.COMPANY_ID, P.POST_TITLE, P.POST_CONTENT, E.EMP_NAME, RC.CITY_NAME, RD.DISTRICT_NAME ,B.BENEFIT_NAME,P.POST_HIT, P.POST_CDATE
FROM POST P, COMPANIES C, EMPLOYMENT E ,REGION_CITY  RC,REGION_DISTRICT RD, BENEFITS B
WHERE P.COMPANY_ID = C.COMPANY_ID 
            AND P.EMP_ID = E.EMP_ID
            AND P.CITY_ID = RC.CITY_ID
            AND  P.DISTRICT_ID = RD.DISTRICT_ID
            AND P.BENEFIT_ID = B.BENEFIT_ID;
 
 